export default [
    {
        "id": "9d2b1c23kxjo938e8-aded8bb182c7",
        "title": "Special Tshirt",
        "description": "Stay stylish and comfortable all day with our premium, ultra-soft cotton t-shirt.",
        "price": "25.00",
        "image": "/products/specialProducts/tshirt.webp",
        "category": "TSHIRTS",
        "quantity": "1",
        "color": "default",
        "size": "md",
    },
    {
        "id": "9d2b1394893480d-45cd-bfb8-aded8bb182c7",
        "title": "Special Hoodie",
        "description": "Wrap yourself in cozy warmth and effortless style with our premium fleece hoodie.",
        "price": "35.00",
        "image": "/products/specialProducts/hoodie.webp",
        "category": "HOODIES",
        "quantity": "1",
        "color": "default",
        "size": "md",
    },
    {
        "id": "eb57ac00-23084edcx1-de1f6139974c",
        "title": "Special Trouser",
        "description": "Experience all-day comfort and sleek style with our perfectly tailored trousers.",
        "price": "20.00",
        "image": "/products/specialProducts/trouser.webp",
        "category": "TROUSERS",
        "quantity": "1",
        "color": "default",
        "size": "md",

    },
    {
        "id": "eb57acj3ye78wedh802b-9bf1-de654r139974c",
        "title": "Special Cap",
        "description": "Top off your look with our comfy, stylish caps made for every adventure.",
        "price": "15.00",
        "image": "/products/specialProducts/cap.webp",
        "category": "CAPS",
        "quantity": "1",
        "color": "default",
        "size": "md",

    },
]