export default [
  {
    "id": "9d2b1c238f-013d-45cd-bfb8-aded8bb182c7",
    "title": "Tshirt",
    "description": "Stay stylish and comfortable all day with our premium, ultra-soft cotton t-shirt.",
    "price": "25.00",
    "image": "/products/tshirts/White.webp",
    "category": "TSHIRTS",
    "quantity": "1",
    "color": "White",
    "size": "md",
    "baseUrl": "/products/tshirts/"
  },
  {
    "id": "9d2b1c6358f-013d-45cd-bfb8-aded8bb182c7",
    "title": "Trouser",
    "description": "Experience all-day comfort and sleek style with our perfectly tailored trousers.",
    "price": "20.00",
    "image": "/products/trousers/White.webp",
    "category": "TROUSERS",
    "quantity": "1",
    "color": "White",
    "size": "md",
    "baseUrl": "/products/trousers/"
  },
  {
    "id": "851900fc-388b-4378-9633-e744c4b422a9",
    "title": "SweatShirt",
    "description": "Stay cozy and stylish all year round with our soft, comfortable sweatshirts.",
    "price": "30.00",
    "image": "/products/sweatshirts/White.webp",
    "category": "SWEATSHIRTS",
    "quantity": "1",
    "color": "White",
    "size": "md",
    "baseUrl": "/products/sweatshirts/"
  },
  {
    "id": "eb57ac00-49f0-402b-9bf1-de1f6139974c",
    "title": "Shorts",
    "description": "Stay cool and comfortable all day with our lightweight, easygoing shorts.",
    "price": "18.00",
    "image": "/products/shorts/White.webp",
    "category": "SHORTS",
    "quantity": "1",
    "color": "White",
    "size": "md",
    "baseUrl": "/products/shorts/"
  },
  {
    "id": "9f178e394a-b69a-4ab8-bf0f-6d00699829c9",
    "title": "Hoodie",
    "description": "Wrap yourself in cozy warmth and effortless style with our premium fleece hoodie.",
    "price": "35.00",
    "image": "/products/hoodies/White.webp",
    "category": "HOODIES",
    "quantity": "1",
    "color": "White",
    "size": "md",
    "baseUrl": "/products/hoodies/"
  },
  {
    "id": "eb57ac00-49f0-402b-9bf1-de654r139974c",
    "title": "Cap",
    "description": "Top off your look with our comfy, stylish caps made for every adventure.",
    "price": "15.00",
    "image": "/products/caps/White.webp",
    "category": "CAPS",
    "quantity": "1",
    "color": "White",
    "size": "md",
    "baseUrl": "/products/caps/"
  },
  {
    "id": "9f178io37f4a-b69a-4ab8-bf0f-6d00699829c9",
    "title": "Notebook",
    "description": "Capture your thoughts, dreams, and ideas in our smooth, durable, and stylish notebook.",
    "price": "5.00",
    "image": "/products/notebooks/White.webp",
    "category": "NOTEBOOKS",
    "quantity": "1",
    "color": "White",
    "size": "md",
    "baseUrl": "/products/notebooks/"
  },
  {
    "id": "851900fc-388b-4378-9633-e973498b422a9",
    "title": "Mug",
    "description": "Sip your favorite drinks in style with our sturdy, cozy, and beautifully designed mugs.",
    "price": "8.00",
    "image": "/products/mugs/White.webp",
    "category": "MUGS",
    "quantity": "1",
    "color": "White",
    "size": "md",
    "baseUrl": "/products/mugs/"
  },
  {
    "id": "851900fc-388b-437kdfy74533-e973498b422a9",
    "title": "Mousepad",
    "description": "Glide through your work or games smoothly with our durable, high-quality mousepads.",
    "price": "12.00",
    "image": "/products/mousepads/White.webp",
    "category": "MOUSEPADS",
    "quantity": "1",
    "color": "White",
    "size": "md",
    "baseUrl": "/products/mousepads/"
  },
  {
    "id": "851900fc-388b-437kdfy74533-09df7e276eedft33",
    "title": "Mobile Cover",
    "description": "Protect your phone in style with our tough, lightweight, and good-looking mobile covers.",
    "price": "10.00",
    "image": "/products/mobilecovers/White.webp",
    "category": "MOBILECOVERS",
    "quantity": "1",
    "color": "White",
    "size": "md",
    "baseUrl": "/products/mobilecovers/"
  },
  {
    "id": "8347rfn9f47rf-437kdfy74533-09df7e276eedft33",
    "title": "Key Chain",
    "description": "Add a touch of personality to your everyday carry with our stylish, durable keychain.",
    "price": "5.00",
    "image": "/products/keychains/White.webp",
    "category": "KEYCHAINS",
    "quantity": "1",
    "color": "White",
    "size": "md",
    "baseUrl": "/products/keychains/"
  },
];