export default [
    {
      "id": "9d2b1c238f-013d-45cd-bfb8-aded8bb182c7",
      "title": "Tshirt",
      "description": "Lightweight, breathable tees to rep the squad in style.",
      "price": "25.99",
      "image": "/products/p1.webp",
      "category": "TSHIRTS",
      "quantity": "1",
      "color": "white",
      "size": "md",
    },
    {
      "id": "9d2b1c6358f-013d-45cd-bfb8-aded8bb182c7",
      "title": "Tshirt",
      "description": "Lightweight, breathable tees to rep the squad in style.",
      "price": "25.99",
      "image": "/products/p2.webp",
      "category": "TSHIRTS",
      "quantity": "1",
      "color": "white",
      "size": "md",
    },
    {
      "id": "eb57ac00-49f0-402b-9bf1-de1f6139974c",
      "title": "Trouser",
      "description": "Comfortable joggers made for gaming and everyday wear.",
      "price": "35.50",
      "image": "/products/p3.webp",
      "category": "TROUSERS",
      "quantity": "1",
      "color": "white",
      "size": "md",

    },
    {
      "id": "eb57ac00-49f0-402b-9bf1-de654r139974c",
      "title": "Trouser",
      "description": "Comfortable joggers made for gaming and everyday wear.",
      "price": "35.50",
      "image": "/products/p4.webp",
      "category": "TROUSERS",
      "quantity": "1",
      "color": "white",
      "size": "md",

    },
    {
      "id": "9f178e394a-b69a-4ab8-bf0f-6d00699829c9",
      "title": "Hoodie",
      "description": "Stay warm and stylish with our ultra-comfy gaming hoodie.",
      "price": "40.50",
      "image": "/products/p5.webp",
      "category": "HOODIES",
      "quantity": "1",
      "color": "white",
      "size": "md",
    },
    {
      "id": "9f178io37f4a-b69a-4ab8-bf0f-6d00699829c9",
      "title": "Hoodie",
      "description": "Stay warm and stylish with our ultra-comfy gaming hoodie.",
      "price": "40.50",
      "image": "/products/p6.webp",
      "category": "HOODIES",
      "quantity": "1",
      "color": "white",
      "size": "md",
    },
    {
      "id": "851900fc-388b-4378-9633-e744c4b422a9",
      "title": "SweatShirt",
      "description": "Soft, cozy, and perfect for gaming or casual wear.",
      "price": "38.75",
      "image": "/products/p7.webp",
      "category": "SWEATSHIRTS",
      "quantity": "1",
      "color": "white",
      "size": "md",
    },
    {
      "id": "851900fc-388b-4378-9633-e973498b422a9",
      "title": "SweatShirt",
      "description": "Soft, cozy, and perfect for gaming or casual wear.",
      "price": "38.75",
      "image": "/products/p8.webp",
      "category": "SWEATSHIRTS",
      "quantity": "1",
      "color": "white",
      "size": "md",
    },
];