export default [
  {
    "id": "9d2b1c238f-013d-45cd-bfb8-aded8bb182c7",
    "title": "Tshirt",
    "description": "Lightweight, breathable tees to rep the squad in style.",
    "price": "20.00",
    "image": "/products/tshirts/White.webp",
    "category": "TSHIRTS",
    "quantity": "1",
    "color": "White",
    "size": "md",
    "baseUrl": "/products/tshirts/"
  },
  {
    "id": "9d2b1c6358f-013d-45cd-bfb8-aded8bb182c7",
    "title": "Trouser",
    "description": "Comfortable joggers made for gaming and everyday wear.",
    "price": "25.99",
    "image": "/products/trousers/White.webp",
    "category": "TROUSERS",
    "quantity": "1",
    "color": "White",
    "size": "md",
    "baseUrl": "/products/trousers/"
  },
  {
    "id": "851900fc-388b-4378-9633-e744c4b422a9",
    "title": "SweatShirt",
    "description": "Soft, cozy, and perfect for gaming or casual wear.",
    "price": "38.75",
    "image": "/products/sweatshirts/White.webp",
    "category": "SWEATSHIRTS",
    "quantity": "1",
    "color": "White",
    "size": "md",
    "baseUrl": "/products/sweatshirts/"
  },
  {
    "id": "eb57ac00-49f0-402b-9bf1-de1f6139974c",
    "title": "Shorts",
    "description": "Comfortable joggers made for gaming and everyday wear.",
    "price": "35.50",
    "image": "/products/shorts/White.webp",
    "category": "SHORTS",
    "quantity": "1",
    "color": "White",
    "size": "md",
    "baseUrl": "/products/shorts/"
  },
  {
    "id": "9f178e394a-b69a-4ab8-bf0f-6d00699829c9",
    "title": "Hoodie",
    "description": "Stay warm and stylish with our ultra-comfy gaming hoodie.",
    "price": "40.50",
    "image": "/products/hoodies/White.webp",
    "category": "HOODIES",
    "quantity": "1",
    "color": "White",
    "size": "md",
    "baseUrl": "/products/hoodies/"
  },
  {
    "id": "eb57ac00-49f0-402b-9bf1-de654r139974c",
    "title": "Cap",
    "description": "Comfortable joggers made for gaming and everyday wear.",
    "price": "35.50",
    "image": "/products/caps/White.webp",
    "category": "CAPS",
    "quantity": "1",
    "color": "White",
    "size": "md",
    "baseUrl": "/products/caps/"
  },
  {
    "id": "9f178io37f4a-b69a-4ab8-bf0f-6d00699829c9",
    "title": "Notebook",
    "description": "Stay warm and stylish with our ultra-comfy gaming hoodie.",
    "price": "40.50",
    "image": "/products/notebooks/White.webp",
    "category": "NOTEBOOKS",
    "quantity": "1",
    "color": "White",
    "size": "md",
    "baseUrl": "/products/notebooks/"
  },
  {
    "id": "851900fc-388b-4378-9633-e973498b422a9",
    "title": "Mug",
    "description": "Soft, cozy, and perfect for gaming or casual wear.",
    "price": "38.75",
    "image": "/products/mugs/White.webp",
    "category": "MUGS",
    "quantity": "1",
    "color": "White",
    "size": "md",
    "baseUrl": "/products/mugs/"
  },
  {
    "id": "851900fc-388b-437kdfy74533-e973498b422a9",
    "title": "Mousepad",
    "description": "Soft, cozy, and perfect for gaming or casual wear.",
    "price": "38.75",
    "image": "/products/mousepads/White.webp",
    "category": "MOUSEPADS",
    "quantity": "1",
    "color": "White",
    "size": "md",
    "baseUrl": "/products/mousepads/"
  },
  {
    "id": "851900fc-388b-437kdfy74533-09df7e276eedft33",
    "title": "Mobile Cover",
    "description": "Soft, cozy, and perfect for gaming or casual wear.",
    "price": "38.75",
    "image": "/products/mobilecovers/White.webp",
    "category": "MOBILECOVERS",
    "quantity": "1",
    "color": "White",
    "size": "md",
    "baseUrl": "/products/mobilecovers/"
  },
  {
    "id": "8347rfn9f47rf-437kdfy74533-09df7e276eedft33",
    "title": "Key Chain",
    "description": "Soft, cozy, and perfect for gaming or casual wear.",
    "price": "38.75",
    "image": "/products/keychains/White.webp",
    "category": "KEYCHAINS",
    "quantity": "1",
    "color": "White",
    "size": "md",
    "baseUrl": "/products/keychains/"
  },
];